conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('root/', admin.site.urls),
    path('',include('lisa.urls')),
    path('auth/',include('users.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lisa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='home'),
    path('to-konveyer/',views.toKonveyer.as_view(),name='to_konveyer'),
    path('konveyer/<int:id>/',views.KonveyerView.as_view(),name='konveyer'),
    path('arizalar/',views.ArizalarView.as_view(),name='arizalar'),
    path('get_user/',views.get_user,name='get_user'),
    path('give_credit/<int:id>/',views.give_credit,name='give_credit'),
    path('reject_credit/<int:id>/',views.reject_credit,name='reject_credit'),
    path('save_number/',views.save_number,name='save_number')

]

users/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.logoutview,name='logout')
]

lisa/models.py
from django.db import models
from users.models import User, Filial
from django.core.validators import MinValueValidator, MaxValueValidator
gender = [
    ('male','Erkak'),
    ('female','Ayol')
]

id = [
    ("id","ID passport"),
    ("old_pass","Eski turdagi passport"),
    ("drivers_license","Haydovchilik guvohnomasi")
]

education = [
    ("1","Oliy"),
    ("2","O‘rta"),
    ("3","O‘rta-maxsus"),
    ("4","Tuganlanmagan oliy"),
    ("5","Boshlang‘ich"),
]

status = [
    ('done','berildi'),
    ('rejected',"rad etildi"),
    ('pending','jarayonda'),
    ('paid','yopilgan')
]

class Client(models.Model):
    # Client's data
    first_name = models.CharField(max_length=100,null=True,blank=True)
    last_name = models.CharField(max_length=100,null=True,blank=True)
    middle_name = models.CharField(max_length=100,null=True,blank=True)
    gender = models.CharField(choices=gender,default='male',max_length=50)
    education = models.CharField(choices=education,default="2",max_length=50)
    birth_date = models.DateField(null=True,blank=True)
    client_country = models.CharField(max_length=50,null=True,blank=True)
    client_region = models.CharField(max_length=50,null=True,blank=True)

    # Passport data
    passport_type = models.CharField(choices=id,default="id",max_length=50,null=True,blank=True)
    passport_serial_letter = models.CharField(max_length=5,null=True,blank=True)
    passport_serial_number = models.CharField(max_length=10,null=True,blank=True)
    passport_pinfl = models.CharField(max_length=50,unique=True,null=True,blank=True)
    passport_got_date = models.DateField(null=True,blank=True)
    passport_expiry_date = models.DateField(null=True,blank=True)
    passport_got_region = models.CharField(max_length=100,null=True,blank=True)
    passport_country = models.CharField(max_length=50,null=True,blank=True)

    # Address data from goverment database
    base_country = models.CharField(max_length=50,null=True,blank=True)
    base_region = models.CharField(max_length=50,null=True,blank=True)
    base_city = models.CharField(max_length=50,null=True,blank=True)
    base_address = models.CharField(max_length=150,null=True,blank=True)

    # Current address data
    current_country = models.CharField(max_length=50,null=True,blank=True)
    current_region = models.CharField(max_length=50,null=True,blank=True)
    current_city = models.CharField(max_length=50,null=True,blank=True)
    current_address = models.CharField(max_length=150,null=True,blank=True)

    # Other data
    description = models.TextField(null=True,blank=True)
    filial = models.ForeignKey(Filial,on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self):
        if self.first_name:
            return self.first_name
        else:
            return "No name"


class Application(models.Model):
    name = models.CharField(max_length=100)
    limit_amount = models.DecimalField(max_digits=10,decimal_places=0)
    rate = models.IntegerField()
    max_month = models.IntegerField()
    fine = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Credit(models.Model):
    # Linkings
    user = models.ForeignKey(User,on_delete=models.SET_NULL, null=True, blank=True)
    client = models.ForeignKey(Client,on_delete=models.SET_NULL,null=True,blank=True)
    contract_id = models.CharField(max_length=50,null=True,blank=True)

    # Credit essentials
    application = models.ForeignKey(Application,on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.DecimalField(max_digits=10,decimal_places=0,default=0)
    pay_day = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(31)],null=True,blank=True)
    rate = models.IntegerField(null=True,blank=True)

    # Dates
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(null=True,blank=True)

    # Other data
    description =  models.TextField(null=True,blank=True)
    status = models.CharField(choices=status,default="pending",max_length=50)
    filial = models.ForeignKey(Filial,on_delete=models.SET_NULL,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.contract_id:
            return self.contract_id
        

class PhoneNumber(models.Model):
    number = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    client = models.ForeignKey(Client,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return f'{self.name} {self.number}'

lisa/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Credit, Application, Client, PhoneNumber
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from users.models import User
from django.http.response import JsonResponse


class IndexView(LoginRequiredMixin,View):
    def get(self,request):
        return render(request,'index.html')
    
class toKonveyer(LoginRequiredMixin,View):
    def get(self,request):
        applications = Application.objects.all()
        return render(request,'application.html',{"applications":applications})
    def post(self,request):
        app_id = request.POST.get('app_btn')
        application = Application.objects.get(id=app_id)
        credit = Credit(
            user=request.user,
            filial=request.user.filial,
            application = application,
            rate = application.rate
        )
        credit.save()
        credit.contract_id = f'F13-{credit.id}'
        credit.save()
        return redirect('konveyer',id=credit.id)
    
class KonveyerView(LoginRequiredMixin,View):
    def get(self,request,id):
        credit = Credit.objects.get(id=id)
        try:
            numbers = PhoneNumber.objects.filter(client_id=credit.client.id).order_by("id")
            return render(request,'konveyer.html',{"credit_id":credit.id,"credit":credit,"numbers":numbers})
        except AttributeError:
            return render(request,'konveyer.html',{"credit_id":credit.id,"credit":credit})
    
class ArizalarView(LoginRequiredMixin,View):
    def get(self,request):
        credits = Credit.objects.filter(filial=request.user.filial).order_by('-created_at')
        return render(request,'arizalar.html',{"credits":credits})
    

@login_required
def get_user(request):
    if request.method == 'POST':
        credit_id = request.POST.get('credit_id')
        credit = Credit.objects.get(id=credit_id)
        try:
            pinfl = request.POST.get('pinfl')
            client = Client.objects.get(passport_pinfl=pinfl)
            credit.client = client
            credit.save()
            return JsonResponse({"status":True})
        except Client.DoesNotExist:
            credit.client = None
            credit.save()
            return JsonResponse({"status":False})
    

@login_required
def save_number(request):
    if request.method == 'POST':
        number = request.POST.get('number')
        client = request.POST.get('client')
        name = request.POST.get('name')
        client_obj = Client.objects.get(id=client)
        if (number and client):
            num = PhoneNumber(
                number = number,
                name = name,
                client = client_obj
            )
            num.save()
            numbers = PhoneNumber.objects.filter(client_id=client_obj.id).order_by("id")
            nums = {}
            for i in numbers:
                nums[i.name] = i.number
            return JsonResponse({"status":True,"numbers":nums})
        return JsonResponse({"status":False})


@login_required
def give_credit(request,id):
    credit = Credit.objects.get(id=id)
    if credit.status != 'rejected' and credit.status != 'paid':
        credit.status = 'done'
        credit.save()
        return redirect('home')
    else:
        return redirect('arizalar')

@login_required
def reject_credit(request,id):
    credit = Credit.objects.get(id=id)
    if credit.status != 'done' and credit.status != 'paid':
        credit.status = 'rejected'
        credit.save()
        return redirect('home')
    else:
        return redirect('arizalar')

lisa/templates/application.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lisa kredit konveyeri</title>
    <!-- <link rel="stylesheet" href="{% static 'css/index_style.css' %}"> -->
</head>
<body>
    <nav>
        <h1><a href="{% url 'home' %}">Lisa Kredit konveyeri</a></h1>
        <select name="" id=""  onchange="send(this)">
            <option value="/"><a href="">-------------------</a></option>
            <option value="{% url 'arizalar' %}"><a href="{% url 'arizalar' %}">Arizalar tarixi</a></option>
        </select>
        <a href="">Dilmuhammad Sodirjon o‘g‘li Abduqodirov</a>
    </nav>
    <div class="main">
        <h1 style="margin-bottom: 25px;color: white;">Kredit maxsulotini tanlang</h1>
        <form method="post">
            {% csrf_token %}
            {% for i in applications %}
            <button class="application" value="{{i.id}}" name="app_btn" type="submit">
                <h1>{{i.name}}</h1>
                <p>Maks. miqdor: {{i.limit_amount|intcomma}}</p>
                <p>Foiz stavkasi: {{i.rate}}</p>
                <p>Maks. muddat: {{i.max_month}} oy</p>
            </button>
            {% endfor %}
        </form>
    </div>
    
</body>
</html>

<script>
    function send(selected){
        window.location.href = selected.value;
    }
</script>


<style>
    :root{
        --pm-color : rgb(20, 82, 107);
        --box-bg : rgba(45, 83, 133, 0.418);
    }
    *{
        margin: 0;
        padding: 0;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }
    body{
        background-color: rgb(18, 148, 105);
    }
    nav{
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        background-color: var(--pm-color);
        padding: 20px;
        font-size: 25px;
        color: white;
        border-bottom: 1px solid rgb(13, 51, 66);
        align-items: center;
    }
    a{
        color: white;
        text-decoration: none;
    }
    select{
        background-color: transparent;
        border: 0;
        color: white;
        font-size: 25px;
    }
    option{
        background-color: transparent;
        color: black;
    }
    .main{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 500px;
        color: rgba(255, 255, 255, 0.842);
        margin-top: 100px;
        margin-bottom: 100px;
    }
    .box-container{
        background-color: rgb(16, 95, 69);
        padding: 200px;
        border-radius: 10px;
        border: 5px solid rgb(11, 61, 44);
    }
    table{
        margin-top: 20px;
        background-color: rgb(28, 116, 86);
        border: 5px solid rgb(197, 197, 197);
        border-radius: 5px;
    }
    td,th{
        border: 3px solid rgb(197, 197, 197);
        padding: 10px;
        font-size: 20px;
        color: white;
    }
    .application{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 10px;
        background-color: rgb(19, 170, 175);
        box-shadow: 3px 3px 0 0 black;
        padding: 10px;
        border-radius: 12px;
        color: white;
        flex:1 1 calc(50% - 20px);
        box-sizing: border-box;
        height: 250px;
        font-size: 20px;
    }
    .application:active{
        background-color: rgb(216, 216, 216);
        box-shadow: 0 0 0 0 black;
        padding: 10px;
        border-radius: 12px;
        color: white;
    }
    form{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 10px;
    }
</style>

lisa/templates/arizalar.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lisa kredit konveyeri</title>
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
</head>
<body>
    <nav>
        <h1><a href="{% url 'home' %}">Lisa Kredit konveyeri</a></h1>
        <select name="" id="" onchange="send(this)">
            <option value="/"><a href="">-------------------</a></option>
            <option value="{% url 'to_konveyer' %}"><a href="{% url 'to_konveyer' %}">Arizani yuborish</a></option>
            <option value="{% url 'arizalar' %}"><a href="{% url 'arizalar' %}">Arizalar tarixi</a></option>
        </select>
        <a href="{% url 'auth:logout' %}">{{user.first_name}} {{user.middle_name}} {{user.last_name}}</a>
    </nav>
    <div class="main">
        <h1 style="color: white;">Arizalar</h1>
        <div class="ariza-container">
            <table>
                <thead>
                    <tr>
                        <td>Contract ID</td>
                        <td>Sana</td>
                        <td>FIO</td>
                        <td>JSHSHIR</td>
                        <td>Ariza miqdori</td>
                        <td>Kredit maxsuloti</td>
                        <td>Foidalanuvchi</td>
                        <td>Filial</td>
                        <td>Xolati</td>
                    </tr>
                </thead>
                <tbody>
                    {% for i in credits %}
                    <tr class="table-data-view">
                        <th style="text-decoration: underline;color: rgb(255, 255, 255);"><a href="{% url 'konveyer' i.id %}">{{i.contract_id}}</a></th>
                        <th>{{i.start_date}}</th>
                        <th>{{i.client.last_name}} {{i.client.first_name}} {{i.client.middle_name}}</th>
                        <th>{{i.client.passport_pinfl}}</th>
                        <th>{{i.amount|intcomma}}</th>
                        <th>{{i.application.name}}</th>
                        <th>{{i.user.first_name}}</th>
                        <th>{{i.filial.name}}</th>
                        <th class="status_{{i.status}}">{% if i.status == "done" %}Bajarildi{% elif i.status == "pending" %}Jarayonda{% elif i.status == "rejected" %}Rad Etildi{% elif i.status == "paid" %}Yopilgan{% endif %}</th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
</body>
</html>

<script>
    function send(selected){
        window.location.href = selected.value;
    }
</script>

<style>
    :root{
    --pm-color : rgb(20, 82, 107);
    --box-bg : rgba(45, 83, 133, 0.418);
  }
  *{
    margin: 0;
    padding: 0;
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
  }
  body{
    background-color: rgb(18, 148, 105);
  }
  nav{
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    background-color: var(--pm-color);
    padding: 20px;
    font-size: 25px;
    color: white;
    border-bottom: 1px solid rgb(13, 51, 66);
    align-items: center;
  }
  a{
    color: white;
    text-decoration: none;
  }
  select{
    background-color: transparent;
    border: 0;
    color: white;
    font-size: 25px;
  }
  option{
    background-color: transparent;
    color: black;
  }
  .main{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 500px;
    color: rgba(255, 255, 255, 0.842);
    margin-top: 100px;
    margin-bottom: 100px;
  }
  .box-container{
    background-color: rgb(16, 95, 69);
    padding: 200px;
    border-radius: 10px;
    border: 5px solid rgb(11, 61, 44);
  }
  .ariza-container{

  }
  table{
    margin-top: 20px;
    background-color: rgb(28, 116, 86);
    border: 5px solid rgb(197, 197, 197);
    border-radius: 5px;
  }
  td,th{
    border: 3px solid rgb(197, 197, 197);
    padding: 10px;
    font-size: 20px;
    color: white;
  }
  .table-data-view{
    border-radius: 13px;
    background-color: rgb(78, 78, 78);
  }
  .status_rejected{
    background-color: rgb(240, 79, 79);
    border-radius: 12px;
  }
  .status_pending{
    background-color: rgb(170, 182, 62);
    border-radius: 12px;
  }
  .status_done{
    background-color: rgb(52, 212, 87);
    border-radius: 12px;
  }
  .status_paid{
    background-color: rgb(180, 180, 180);
    border-radius: 12px;
  }
</style>

lisa/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lisa kredit konveyeri</title>
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
</head>
<body>
    <nav>
        <h1><a href="{% url 'home' %}">Lisa Kredit konveyeri</a></h1>
        <select name="" id="" onchange="send(this)">
            <option value="/"><a href="">-------------------</a></option>
            <option value="{% url 'to_konveyer' %}"><a href="{% url 'to_konveyer' %}">Arizani yuborish</a></option>
            <option value="{% url 'arizalar' %}"><a href="{% url 'arizalar' %}">Arizalar tarixi</a></option>
        </select>
        <a href="{% url 'auth:logout' %}">{{user.first_name}} {{user.middle_name}} {{user.last_name}}</a>
    </nav>
    <div class="main">
        <div class="box-container">
            <h1>Vazifa kutilmoqda...</h1>
        </div>
    </div>
    
</body>
</html>

<script>
    function send(selected){
        window.location.href = selected.value;
    }
</script>